### ISSUE TITLE
Ajout lien Slack

### ISSUE THREAD

**Issue by abelards** [parisrb/rubyparis.org#20]
http://parisrb-slack-invite.herokuapp.com/

**Comment by abelards** [comment]
À modifier ici => en langage de template "slim"
https://github.com/parisrb/rubyparis.org/blob/master/app/views/shared/_navbar.html.slim

**Comment by abelards** [comment]
lien à ajouter : http://parisrb-slack-invite.herokuapp.com/

**Comment by nasreddineboukehil** [comment]
Bonsoir Sylvain,

je pense que cet issue peut être fermer après le merge de #21.

j'ai cette erreur après le fork et clone: ``` rake aborted!
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ```

**Comment by abelards** [comment]
As-tu configuré ta base de données ? Je pense qu'il cherche un sqlite et ne le trouve pas.
Merci et à bientôt pour de nouvelles contribs :)
